version: '3.8'

services:
  app:
    container_name: chat-nuff-bot
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_USE_TLS=${REDIS_USE_TLS} # No TLS during local dev
      - REDIS_TIMEOUT=${REDIS_TIMEOUT} # seconds
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - redis

  redis:
    container_name: message-storage
    image: redis:7.2.4-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
