[project]
name = "chat-nuff-bot"
version = "0.0.1"
requires-python = ">=3.12"
readme = "README.md"

dependencies = [
    "cryptography==45.0.6",
    "httpx>=0.28.0",
    "litellm==1.88.1",
    "openai>=2.20.0,<3.0.0",
    "pydantic>=2.10.0,<3.0.0",
    "python-dotenv==1.0.1",
    "python-telegram-bot>=21.6,<22.0",
    "redis==5.0.4",
    "starlette==0.37.2",
    "tqdm==4.66.2",
    "uvicorn==0.29.0"
]


[tool.ruff]
line-length = 120
exclude = [
    "__init__.py",
]

[tool.pytest.ini_options]
pythonpath = ["src"]

[dependency-groups]
dev = [
    "fakeredis>=2.31.0",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "pytest-mock>=3.14.1",
    "pytest-spec>=5.0.0",
    "pytest-xdist>=3.8.0",
    "ruff>=0.12.11",
]


